import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Layout from '@/components/coffee/Layout';
import { useCart } from '@/context/CartContext';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/hooks/use-toast';
import { ArrowLeft, ArrowRight, Check, Loader2, Package, MapPin, CreditCard } from 'lucide-react';
import { shippingAddressSchema, type ShippingAddressInput } from '@/lib/validation';
import logger from '@/lib/logger';

type CheckoutStep = 'shipping' | 'review' | 'payment';

interface ShippingForm {
  fullName: string;
  email: string;
  phone: string;
  addressLine1: string;
  addressLine2: string;
  city: string;
  state: string;
  pincode: string;
  landmark: string;
}

const Checkout = () => {
  const { cartItems, getCartTotal, clearCart } = useCart();
  const { user } = useAuth();
  const navigate = useNavigate();
  const { toast } = useToast();

  const [step, setStep] = useState<CheckoutStep>('shipping');
  const [isLoading, setIsLoading] = useState(false);
  const [orderId, setOrderId] = useState<string | null>(null);

  const [shippingForm, setShippingForm] = useState<ShippingForm>({
    fullName: '',
    email: user?.email || '',
    phone: '',
    addressLine1: '',
    addressLine2: '',
    city: '',
    state: '',
    pincode: '',
    landmark: '',
  });

  const steps: { id: CheckoutStep; label: string; icon: React.ReactNode }[] = [
    { id: 'shipping', label: 'Shipping', icon: <MapPin className="w-4 h-4" /> },
    { id: 'review', label: 'Review', icon: <Package className="w-4 h-4" /> },
    { id: 'payment', label: 'Payment', icon: <CreditCard className="w-4 h-4" /> },
  ];

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setShippingForm(prev => ({
      ...prev,
      [e.target.name]: e.target.value
    }));
  };

  const validateShipping = (): boolean => {
    const result = shippingAddressSchema.safeParse(shippingForm);
    
    if (!result.success) {
      // Get the first error to display
      const firstError = result.error.errors[0];
      toast({
        title: 'Validation Error',
        description: firstError?.message || 'Please check your shipping details',
        variant: 'destructive',
      });
      return false;
    }
    
    return true;
  };

  const handleNextStep = () => {
    if (step === 'shipping' && !validateShipping()) return;
    
    const stepOrder: CheckoutStep[] = ['shipping', 'review', 'payment'];
    const currentIndex = stepOrder.indexOf(step);
    if (currentIndex < stepOrder.length - 1) {
      setStep(stepOrder[currentIndex + 1]);
    }
  };

  const handlePrevStep = () => {
    const stepOrder: CheckoutStep[] = ['shipping', 'review', 'payment'];
    const currentIndex = stepOrder.indexOf(step);
    if (currentIndex > 0) {
      setStep(stepOrder[currentIndex - 1]);
    }
  };

  const handlePlaceOrder = async () => {
    setIsLoading(true);
    try {
      // Create order
      const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert({
          user_id: user?.id,
          order_number: '', // Will be generated by trigger
          subtotal: getCartTotal(),
          total_amount: getCartTotal(),
          shipping_address: {
            full_name: shippingForm.fullName,
            phone: shippingForm.phone,
            address_line1: shippingForm.addressLine1,
            address_line2: shippingForm.addressLine2,
            city: shippingForm.city,
            state: shippingForm.state,
            pincode: shippingForm.pincode,
            landmark: shippingForm.landmark,
          },
          status: 'pending',
          payment_status: 'pending',
        })
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems = cartItems.map(item => ({
        order_id: order.id,
        product_name: item.product.name,
        weight: item.weight,
        quantity: item.quantity,
        unit_price: item.product.price,
        total_price: item.product.price * item.quantity,
      }));

      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(orderItems);

      if (itemsError) throw itemsError;

      setOrderId(order.order_number);
      clearCart();
      
      toast({
        title: 'Order Placed!',
        description: 'Your order has been placed successfully',
      });

      // In production, redirect to payment gateway here
      // For now, show success state
      setStep('payment');
    } catch (error: unknown) {
      logger.error('Order placement failed', error);
      const errorMessage = error instanceof Error ? error.message : 'Failed to place order';
      toast({
        title: 'Order Failed',
        description: errorMessage.includes('Invalid') ? errorMessage : 'An error occurred while placing your order. Please try again.',
        variant: 'destructive',
      });
    } finally {
      setIsLoading(false);
    }
  };

  if (cartItems.length === 0 && !orderId) {
    navigate('/cart');
    return null;
  }

  return (
    <Layout>
      <div className="min-h-screen bg-background py-8">
        <div className="container mx-auto px-4 max-w-4xl">
          {/* Progress Steps */}
          <div className="mb-8">
            <div className="flex items-center justify-center gap-4">
              {steps.map((s, index) => (
                <div key={s.id} className="flex items-center">
                  <div
                    className={`
                      flex items-center gap-2 px-4 py-2 rounded-full text-sm font-medium transition-all
                      ${step === s.id
                        ? 'bg-primary text-primary-foreground'
                        : steps.indexOf(steps.find(st => st.id === step)!) > index
                          ? 'bg-green-600 text-white'
                          : 'bg-muted text-muted-foreground'
                      }
                    `}
                  >
                    {steps.indexOf(steps.find(st => st.id === step)!) > index ? (
                      <Check className="w-4 h-4" />
                    ) : (
                      s.icon
                    )}
                    <span className="hidden sm:inline">{s.label}</span>
                  </div>
                  {index < steps.length - 1 && (
                    <div className="w-8 h-0.5 bg-border mx-2" />
                  )}
                </div>
              ))}
            </div>
          </div>

          <div className="grid gap-6 lg:grid-cols-3">
            {/* Main Content */}
            <div className="lg:col-span-2">
              {step === 'shipping' && (
                <div className="bg-card border border-border rounded-xl p-6">
                  <h2 className="text-xl font-semibold mb-6 flex items-center gap-2">
                    <MapPin className="w-5 h-5 text-primary" />
                    Shipping Details
                  </h2>

                  <div className="grid gap-4 sm:grid-cols-2">
                    <div className="sm:col-span-2">
                      <Label htmlFor="fullName">Full Name *</Label>
                      <Input
                        id="fullName"
                        name="fullName"
                        value={shippingForm.fullName}
                        onChange={handleInputChange}
                        placeholder="John Doe"
                        className="mt-1"
                      />
                    </div>

                    <div>
                      <Label htmlFor="email">Email</Label>
                      <Input
                        id="email"
                        name="email"
                        type="email"
                        value={shippingForm.email}
                        onChange={handleInputChange}
                        placeholder="john@example.com"
                        className="mt-1"
                        disabled
                      />
                    </div>

                    <div>
                      <Label htmlFor="phone">Phone Number *</Label>
                      <Input
                        id="phone"
                        name="phone"
                        type="tel"
                        value={shippingForm.phone}
                        onChange={handleInputChange}
                        placeholder="9876543210"
                        maxLength={10}
                        className="mt-1"
                      />
                    </div>

                    <div className="sm:col-span-2">
                      <Label htmlFor="addressLine1">Address Line 1 *</Label>
                      <Input
                        id="addressLine1"
                        name="addressLine1"
                        value={shippingForm.addressLine1}
                        onChange={handleInputChange}
                        placeholder="House/Flat No., Building Name"
                        className="mt-1"
                      />
                    </div>

                    <div className="sm:col-span-2">
                      <Label htmlFor="addressLine2">Address Line 2</Label>
                      <Input
                        id="addressLine2"
                        name="addressLine2"
                        value={shippingForm.addressLine2}
                        onChange={handleInputChange}
                        placeholder="Street, Area"
                        className="mt-1"
                      />
                    </div>

                    <div>
                      <Label htmlFor="city">City *</Label>
                      <Input
                        id="city"
                        name="city"
                        value={shippingForm.city}
                        onChange={handleInputChange}
                        placeholder="Mumbai"
                        className="mt-1"
                      />
                    </div>

                    <div>
                      <Label htmlFor="state">State *</Label>
                      <Input
                        id="state"
                        name="state"
                        value={shippingForm.state}
                        onChange={handleInputChange}
                        placeholder="Maharashtra"
                        className="mt-1"
                      />
                    </div>

                    <div>
                      <Label htmlFor="pincode">Pincode *</Label>
                      <Input
                        id="pincode"
                        name="pincode"
                        value={shippingForm.pincode}
                        onChange={handleInputChange}
                        placeholder="400001"
                        maxLength={6}
                        className="mt-1"
                      />
                    </div>

                    <div>
                      <Label htmlFor="landmark">Landmark</Label>
                      <Input
                        id="landmark"
                        name="landmark"
                        value={shippingForm.landmark}
                        onChange={handleInputChange}
                        placeholder="Near..."
                        className="mt-1"
                      />
                    </div>
                  </div>
                </div>
              )}

              {step === 'review' && (
                <div className="space-y-6">
                  {/* Shipping Address Summary */}
                  <div className="bg-card border border-border rounded-xl p-6">
                    <div className="flex items-center justify-between mb-4">
                      <h2 className="text-lg font-semibold flex items-center gap-2">
                        <MapPin className="w-5 h-5 text-primary" />
                        Shipping Address
                      </h2>
                      <button
                        onClick={() => setStep('shipping')}
                        className="text-sm text-primary hover:underline"
                      >
                        Edit
                      </button>
                    </div>
                    <div className="text-muted-foreground">
                      <p className="font-medium text-foreground">{shippingForm.fullName}</p>
                      <p>{shippingForm.addressLine1}</p>
                      {shippingForm.addressLine2 && <p>{shippingForm.addressLine2}</p>}
                      <p>{shippingForm.city}, {shippingForm.state} - {shippingForm.pincode}</p>
                      <p>Phone: {shippingForm.phone}</p>
                    </div>
                  </div>

                  {/* Order Items */}
                  <div className="bg-card border border-border rounded-xl p-6">
                    <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
                      <Package className="w-5 h-5 text-primary" />
                      Order Items
                    </h2>
                    <div className="space-y-4">
                      {cartItems.map((item) => (
                        <div
                          key={`${item.product.id}-${item.weight}`}
                          className="flex gap-4 pb-4 border-b border-border last:border-0 last:pb-0"
                        >
                          <div className="w-16 h-16 rounded-lg overflow-hidden bg-muted flex-shrink-0">
                            <img
                              src={item.product.image_url || item.product.images?.[0] || ''}
                              alt={item.product.name}
                              className="w-full h-full object-cover"
                            />
                          </div>
                          <div className="flex-1 min-w-0">
                            <p className="font-medium text-foreground truncate">{item.product.name}</p>
                            <p className="text-sm text-muted-foreground">
                              {item.weight >= 1000 ? `${item.weight / 1000} kg` : `${item.weight}g`} • Qty: {item.quantity}
                            </p>
                          </div>
                          <p className="font-semibold text-foreground">
                            ₹{item.product.price * item.quantity}
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              )}

              {step === 'payment' && orderId && (
                <div className="bg-card border border-border rounded-xl p-8 text-center">
                  <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-green-600/20 mb-6">
                    <Check className="w-8 h-8 text-green-600" />
                  </div>
                  <h2 className="text-2xl font-serif font-bold text-foreground mb-2">
                    Order Placed Successfully!
                  </h2>
                  <p className="text-muted-foreground mb-4">
                    Your order <span className="font-medium text-foreground">{orderId}</span> has been placed.
                  </p>
                  <p className="text-sm text-muted-foreground mb-6">
                    We'll send you an email confirmation shortly.
                  </p>
                  <Button onClick={() => navigate('/')} className="gap-2">
                    Continue Shopping
                    <ArrowRight className="w-4 h-4" />
                  </Button>
                </div>
              )}

              {step === 'payment' && !orderId && (
                <div className="bg-card border border-border rounded-xl p-6">
                  <h2 className="text-xl font-semibold mb-6 flex items-center gap-2">
                    <CreditCard className="w-5 h-5 text-primary" />
                    Payment
                  </h2>
                  <p className="text-muted-foreground mb-6">
                    Payment gateway integration (Razorpay) coming soon. For now, orders are placed as COD.
                  </p>
                  <Button
                    onClick={handlePlaceOrder}
                    disabled={isLoading}
                    className="w-full h-12 text-base font-medium"
                  >
                    {isLoading ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        Placing Order...
                      </>
                    ) : (
                      <>
                        Place Order (COD)
                        <ArrowRight className="w-4 h-4 ml-2" />
                      </>
                    )}
                  </Button>
                </div>
              )}

              {/* Navigation Buttons */}
              {step !== 'payment' && (
                <div className="flex justify-between mt-6">
                  <Button
                    variant="outline"
                    onClick={handlePrevStep}
                    disabled={step === 'shipping'}
                    className="gap-2"
                  >
                    <ArrowLeft className="w-4 h-4" />
                    Back
                  </Button>
                  <Button onClick={handleNextStep} className="gap-2">
                    {step === 'review' ? 'Proceed to Payment' : 'Continue'}
                    <ArrowRight className="w-4 h-4" />
                  </Button>
                </div>
              )}
            </div>

            {/* Order Summary Sidebar */}
            {!orderId && (
              <div className="lg:col-span-1">
                <div className="bg-card border border-border rounded-xl p-6 sticky top-24">
                  <h2 className="text-lg font-semibold text-foreground mb-4">
                    Order Summary
                  </h2>

                  <div className="space-y-3 text-sm">
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">
                        Items ({cartItems.reduce((acc, item) => acc + item.quantity, 0)})
                      </span>
                      <span className="font-medium">₹{getCartTotal()}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Shipping</span>
                      <span className="font-medium text-green-600">Free</span>
                    </div>
                    <div className="border-t border-border pt-3 mt-3">
                      <div className="flex justify-between text-base">
                        <span className="font-semibold">Total</span>
                        <span className="font-bold text-primary">₹{getCartTotal()}</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Checkout;
