import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders, status: 200 });
  }

  try {
    const { razorpayOrderId, razorpayPaymentId, razorpaySignature, checkoutData } = await req.json();

    if (!razorpayOrderId || !razorpayPaymentId || !razorpaySignature) {
      return new Response(
        JSON.stringify({ error: 'Missing required payment verification fields' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const razorpayKeySecret = Deno.env.get('RAZORPAY_KEY_SECRET');
    if (!razorpayKeySecret) {
      throw new Error('Razorpay secret not configured');
    }

    // Verify signature using Web Crypto API
    const body = razorpayOrderId + '|' + razorpayPaymentId;
    const encoder = new TextEncoder();
    const keyData = encoder.encode(razorpayKeySecret);
    const messageData = encoder.encode(body);
    
    const key = await crypto.subtle.importKey(
      'raw',
      keyData,
      { name: 'HMAC', hash: 'SHA-256' },
      false,
      ['sign']
    );
    
    const signature = await crypto.subtle.sign('HMAC', key, messageData);
    const expectedSignature = Array.from(new Uint8Array(signature))
      .map(b => b.toString(16).padStart(2, '0'))
      .join('');

    if (expectedSignature !== razorpaySignature) {
      return new Response(
        JSON.stringify({ error: 'Invalid payment signature', verified: false }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Payment verified - now create the order
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Parse checkout data
    const checkout = checkoutData ? JSON.parse(checkoutData) : null;
    
    if (!checkout) {
      throw new Error('Checkout data is required');
    }

    // Check for duplicate order (idempotency)
    const { data: existingOrder } = await supabase
      .from('orders')
      .select('id, order_number, payment_status')
      .eq('razorpay_order_id', razorpayOrderId)
      .maybeSingle();

    if (existingOrder) {
      console.log('Order already exists for this payment:', existingOrder.id);
      return new Response(
        JSON.stringify({ 
          verified: true, 
          message: 'Order already created for this payment',
          orderId: existingOrder.id,
          orderNumber: existingOrder.order_number,
          paymentStatus: existingOrder.payment_status,
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Create order after successful payment verification
    const { data: order, error: orderError } = await supabase
      .from('orders')
      .insert({
        user_id: checkout.user_id,
        order_number: '', // Will be generated by trigger
        subtotal: checkout.subtotal,
        total_amount: checkout.total_amount,
        shipping_address: checkout.shipping_address,
        pincode: checkout.pincode,
        shipping_region: checkout.shipping_region,
        shipping_amount: checkout.shipping_charge,
        shipping_charge: checkout.shipping_charge,
        payment_type: checkout.payment_type,
        payment_method: checkout.payment_type === 'cod' ? 'Cash on Delivery' : 'Online Payment',
        cod_advance_paid: checkout.cod_advance_paid || 0,
        cod_handling_fee: checkout.cod_handling_fee || 0,
        cod_balance: checkout.cod_balance || 0,
        razorpay_order_id: razorpayOrderId,
        razorpay_payment_id: razorpayPaymentId,
        payment_status: checkout.payment_type === 'cod' ? 'advance_paid' : 'paid',
        payment_verified: true,
        payment_verified_at: new Date().toISOString(),
        status: 'confirmed',
      })
      .select()
      .single();

    if (orderError) {
      console.error('Order creation error:', orderError);
      throw new Error(`Failed to create order: ${orderError.message}`);
    }

    // Create order items
    if (checkout.items && checkout.items.length > 0) {
      const orderItems = checkout.items.map((item: any) => ({
        order_id: order.id,
        product_name: item.product_name,
        product_id: item.product_id || null,
        weight: item.weight,
        grind_type: item.grind_type || 'Whole Bean',
        quantity: item.quantity,
        unit_price: item.unit_price,
        total_price: item.total_price,
        variant_id: item.variant_id || null,
      }));

      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(orderItems);

      if (itemsError) {
        console.error('Order items creation error:', itemsError);
        // Don't fail the whole transaction - order is created
      }
    }

    // TODO: Reduce inventory for products
    // TODO: Send order confirmation email

    return new Response(
      JSON.stringify({ 
        verified: true, 
        message: 'Payment verified and order created successfully',
        orderId: order.id,
        orderNumber: order.order_number,
        paymentStatus: checkout.payment_type === 'cod' ? 'advance_paid' : 'paid',
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error: unknown) {
    console.error('Error verifying payment:', error);
    const message = error instanceof Error ? error.message : 'Unknown error';
    return new Response(
      JSON.stringify({ error: message, verified: false }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
