import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { createHmac } from "https://deno.land/std@0.168.0/node/crypto.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { razorpayOrderId, razorpayPaymentId, razorpaySignature, checkoutData } = await req.json();

    if (!razorpayOrderId || !razorpayPaymentId || !razorpaySignature) {
      return new Response(
        JSON.stringify({ error: 'Missing required payment verification fields' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const razorpayKeySecret = Deno.env.get('RAZORPAY_KEY_SECRET');
    if (!razorpayKeySecret) {
      throw new Error('Razorpay secret not configured');
    }

    // Verify signature
    const body = razorpayOrderId + '|' + razorpayPaymentId;
    const expectedSignature = createHmac('sha256', razorpayKeySecret)
      .update(body)
      .digest('hex');

    if (expectedSignature !== razorpaySignature) {
      return new Response(
        JSON.stringify({ error: 'Invalid payment signature', verified: false }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Payment verified - now create the order
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Parse checkout data
    const checkout = checkoutData ? JSON.parse(checkoutData) : null;
    
    if (!checkout) {
      throw new Error('Checkout data is required');
    }

    // Create order after successful payment verification
    const { data: order, error: orderError } = await supabase
      .from('orders')
      .insert({
        user_id: checkout.user_id,
        order_number: '', // Will be generated by trigger
        subtotal: checkout.subtotal,
        total_amount: checkout.total_amount,
        shipping_address: checkout.shipping_address,
        pincode: checkout.pincode,
        shipping_region: checkout.shipping_region,
        shipping_charge: checkout.shipping_charge,
        payment_type: checkout.payment_type,
        cod_advance_paid: checkout.cod_advance_paid,
        cod_handling_fee: checkout.cod_handling_fee,
        cod_balance: checkout.cod_balance,
        razorpay_order_id: razorpayOrderId,
        razorpay_payment_id: razorpayPaymentId,
        payment_status: checkout.payment_type === 'cod' ? 'advance_paid' : 'paid',
        status: 'confirmed',
      })
      .select()
      .single();

    if (orderError) {
      console.error('Order creation error:', orderError);
      throw new Error(`Failed to create order: ${orderError.message}`);
    }

    // Create order items
    if (checkout.items && checkout.items.length > 0) {
      const orderItems = checkout.items.map((item: any) => ({
        order_id: order.id,
        product_name: item.product_name,
        weight: item.weight,
        quantity: item.quantity,
        unit_price: item.unit_price,
        total_price: item.total_price,
        variant_id: item.variant_id || null,
      }));

      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(orderItems);

      if (itemsError) {
        console.error('Order items creation error:', itemsError);
        // Don't fail the whole transaction - order is created
      }
    }

    return new Response(
      JSON.stringify({ 
        verified: true, 
        message: 'Payment verified and order created successfully',
        orderId: order.id,
        orderNumber: order.order_number,
        paymentStatus: checkout.payment_type === 'cod' ? 'advance_paid' : 'paid',
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error: unknown) {
    console.error('Error verifying payment:', error);
    const message = error instanceof Error ? error.message : 'Unknown error';
    return new Response(
      JSON.stringify({ error: message, verified: false }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});